config/routes.rb
Rails.application.routes.draw do

  root 'public#index'
  get 'login' => 'accounts#login', as: :login
  get 'logout' => 'accounts#logout', as: :logout
  post 'authenticate' => 'accounts#authenticate', as: :authenticate
  get 'public/:listing_id/details' => 'public#details', as: :details
resources :users do
resources :listings do
resources :features
resources :pictures
end
end

end

app/models/feature.rb
class Feature < ActiveRecord::Base
	validates :description, presence: true
	belongs_to :listing
end

app/models/listing.rb
class Listing < ActiveRecord::Base 
validates :title, presence: true
belongs_to :user
validates :title, length: {maximum: 150}
has_many :features, dependent: :destroy
has_many :picture, dependent: :destroy 
end

app/models/picture.rb
class Picture < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	
 has_secure_password

has_many :listings 

validates :firstname, presence: true
validates :lastname, presence: true 
validates :email, presence: true 
validates :password, length: {minimum: 8}, allow_nil: true 
validates :usertype, presence: true 
validates :usertype, presence: true 

def to_s
	"#{firstname}" +" " + "#{lastname}"

	
end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

def login
end

def logout
	@user = User.find(session[:user_id])
	session[:user_id] = nil 
end

def authenticate
	user = User.find_by_email(params[:email])
	if user != nil && user.authenticate(params[:password])
	session[:user_id] = user.user.id
	if user.usertype == 'Admin'
		redirect_to user_listings_path(user)
	else 
		redirect_to users_path
	end 
else 
	redirect_to login_path 
		

		end 
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	User.where(id: session[:user_id]).first
  end

  helper_method :current_user

  def logged_in
  	if session[:user_id] == nil
  		redirect_to login_path
  	end
  end

helper_method :logged_in

  def is_authorized(required_usertype)
  	user = User.find(session[:user_id])
  	if user.usertype != required_usertype
  		session[:user_id] = nil 
  		redirect_to login_path
end
else
  redirect_to login_path
end 
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  def index
  	listingId = params[:listing_id]
  	@listing = Listing.find(listingId)
  	@features = @listing.features
  end

  def new
  end

  def create 
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def features_params
  	params.require(:feature).permit(:listing_id, :description)
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :logged_in
  
def index	
	@user = User.find(param[:user_id])
  	@listings = @user.listings.all

end


def new
	@user = User.find(params[:user_id])
	@listing = Listing.new(:user => @user)

end

def create
@user = User.find(params[:user_id])
@listing = Listing.new (listing_params)
@listing.user = @user

if @listing.save

redirect_to root_path 

else

render "new" 

end
end

def edit
# id = params[:id]
# @listing = Listing.find(id)
end

def update
# id = params[:id]
# @listing = Listing.find(id) if @listing.update
# redirect_to root_path else
# render "edit" 
end
end

def destroy
# id = params[:id]
# @listing = Listing.find(id) 
# @listing.destroy

# redirect_to root_path
end

def show 
end


private

def listing_params

params.require(:listing).permit(:user_id, :title, :description, :price,) 

end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

def index
@iser = User.find(params[:user_id])
@listing = @user.listing.find(params[:listing_id])
@pictures = @listing.pictures
end

def show 
	@listing = Listing.find(params[:listing_id])
	@picture = @listing.pictures.find(params[:id])
def new
	listingId = params[:listing_id]
	@listing = Listing.find(listingId)
	@picture = Picture.new(:listing=>@listing)
end

def create
	listingId = params[:listing_id]
	@listing = Listing.find(listingId)
	@picture = Picture.new(pictures_params)
	@picture.listing = @listing

	uploadedIO = params[:picture][:image]
	if uploadedIO != nil
		t = Time.now
		ext = File.extname(uploadedIO.original_filename)
		tmpFileName = "file_#{t.strftime("%Y%m%d%H%M")}" + ext
		filename = Rails.root.join('public','images', tmpFileName)
		@picture.filename = tmpFileName


	File.open(filename, 'wb') do |file|
		file.write(uploadedIO.read)
	end

if @picture.save
	redirect_to listing_pictures_path
else
	render 'new'
end 
end

end

def edit
	@listing = Listing.find(params[:listingId])
	@picture = @listing.pictures.flind(params[:id])
end

def update
	listingId = params[:listing_id]
	@listing = Listing.find(listingId)

	@picture = @listing.pictures.flind(params[:id])
	uploadIO = params[:picture][:image]

	if uploadIO != nil
if @picture.filename != nil
filename = Rails.root.join('public','images',@picture.filename) 
File.delete(filename) if File.exist?(filename)

end

t = Time.now
ext = File.extname(uploadIO.original_filename) 
tmpFilename = "file_#{t.strftime("%Y%m%d%H%M")}" + ext

@picture.filename = tmpFilename

filename = Rails.root.join('public','images',tmpFilename) 
File.open(filename, 'wb') do |file|
file.write(uploadIO.read)

end
end

if @picture.update(pictures_params)
redirect_to listing_pictures_path(@listing)

else
render 'edit'
end 
end

def destroy
	listingId = params[:listing_id]
	listing = Listing.find(listingId)
	picture = listing.pictures.find(params[:id])
	if picture.filename != nil
	filename = Rails.root.join('public','images',picture.filename)
	File.delete(filename) if File.exist?(filename)
end
listing.pictures.destroy(picture)
redirect_to listing_pictures_path(listing)
end

private
def pictures_params
	params.require(:picture).permit(:listing_id, :title)
end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController 
	layout 'public'
def index
@listings = Listing.all
@pictures = [] 
@listings.each do |listing|
	listing.pictures.each do |pic| 
		@pictures.push pic
		end 
	end
end

def details

@listing = Listing.find(params[:listing_id])

	end 
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in
  before_action :checkAuth
  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

private 
def checkAuth
  is_authorized ('Admin')
end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accounts/login.html.erb
<h1 class='page-header'>Login </h1>
<% form_tag authenticate_url, :class => 'form-horizontal' do %>
<div class='form-group'>
<div class='col-sm-2'>

<%= label_tag (:email, 'Email Address') %>
</div>
<div class='col-sm-6'>
<%= email_tag :email, "", :class=> 'form-control', :autofocus =>'autofocus' %>


</div>
</div>

<div class='form-group'>
<div class='col-sm-2'>
<%= label_tag (:password, 'Password') %>
</div>
<div class= 'col-sm-6'>
<%= password_tag :password, "", class => 'form-control', :autofocust => 'autofocus'
%>
</div>
</div>

<%= submit_tag('Log In', :class=>'btn btn-primary btn-md') %>

<% end %>

app/views/accounts/logout.html.erb
<h1>Logout
	<small><%= @user.to_s %></small><h1> 
	<br/>
	<%= link_to 'Login', login_path %> 
	

app/views/features/index.html.erb
<h1 class='page-heading'>All Features <small><%=@listing.title%></small> </h1>
<div class="row">
<div class="col-md-12">
<%= link_to 'New',new_listing_feature_path , {class: 'btn btn-primary btn-md'} %> </div>
</div>
<div class="row">
<div class="col-md-12">
<% if @features.length == 0 %>
<p class="lead">No features found </p> <% else %>
<table class="table table-bordered table-striped table-responsive"> <thead>
<tr> <td>Description</td> <td></td>
<td></td>
</tr>
</thead> <tbody>
<% @features.each do |feature| %> <tr>
<td><%= feature.description %> </td>
<td><%= link_to 'Edit', edit_listing_feature_path(@listing,feature) %></td>
<td><%= link_to 'Delete', [@listing,feature], method:delete, data:{confirm: 'Are you sure'} %></td>
</tr>
<% end %> </tbody>
</table>
<% end %>
</div> </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Realestate</title>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

	
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html> <html>
<head>
<title>Listings</title>
<%= stylesheet_link_tag %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %> <%= csrf_meta_tags %>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta name="description" content=""> <meta name="author" content=""> <link rel="icon" href="../../favicon.ico">
<title>Starter Template for Bootstrap</title>
<!-- Bootstrap core CSS -->
<link href="../../dist/css/bootstrap.min.css" rel="stylesheet">
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">
<!-- Custom styles for this template -->
<link href="starter-template.css" rel="stylesheet">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries --> <!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script> <![endif]-->
</head> <body>
<nav class="navbar navbar-default navbar-fixed-top"> <div class="container">
<div class="navbar-header">
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data- target="#navbar" aria-expanded="false" aria-controls="navbar">
<span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<%= link_to 'Awesome Agency', root_path, :class => 'navbar-brand' %> <!--<a class="navbar-brand" href="#"></a>-->
</div>
<div id="navbar" class="collapse navbar-collapse">
<ul class="nav navbar-nav">
<li class="active"><a href="#">Home</a></li> <li><a href="#about">About</a></li>
<li><a href="#contact">Contact</a></li> </ul>
</div><!--/.nav-collapse --> </div>
</nav>
<div class="container"> <%= yield %>
</div>
</body>
</html>

app/views/listings/_form.html.erb
<%= form_for @listing, :html =>{:multipart => true, :class => 'form-horizontal' } do |f| %> <% if @listing.errors.any? %>
<div class='form-group'>
<div id="error_explanation">
<h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>
<ul>
<% @listing.errors.full_messages.each do |message| %>
<li><%= message %></li> <% end %>
</ul>
</div>
</div> <% end %>
<div class='form-group'>
<div class='control-label col-md-2'>
<%= f.label :title %>

</div>
<div class='col-md-4'>
<%= f.text_field :title, {:class => 'form-control input-md', :maxlength => '140'} %> </div>
</div>
<div class='form-group'>
<div class='control-label col-md-2'>
<%= f.label :description %> </div>
<div class='col-md-6'>
<%= f.text_field :description, {:class => 'form-control input-md', :maxlength => '140', :rows => '4', :cols => '30'} %>
</div>
</div>





<div class='form-group'>
<div class='control-label col-md-2'>
Select files </div>
<div class='col-md-4'>
<%= f.file_field 'images', {:class => 'form-control input-md', :multiple => 'multiple'} %>

</div> </div>
<div class='form-group'>
<div class='col-md-6 text-center'>
<%= f.submit "Save", class: 'btn btn-primary btn-md' %> </div>
</div>
<% end %>

app/views/listings/edit.html.erb
<h1>Edit Listing</h1>
<%= render 'form' %>
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<h1 class="page-heading">All Listings</h1> <div class="row">
<div class='form-group'>
<div class="col-md-12">
<%=link_to 'New', new_user_listing_path(@user), {class: 'btn btn-primary btn-md'} %>
</div>
</div> </div>
<br/>
<div class="row">
<div class="col-md-12">
<% if @listings.length == 0 %>
<p class="lead">No listings found </p>
<% else %>
<table class="table table-bordered table-striped table-responsive"> <thead>
<tr>
<td>Title</td> 
<td>Description</td> 
<td>Price</td>
<td></td>

</tr>
</thead> <tbody>
<% @listings.each do |listing| %> <tr>

<td><%= listing.title %> </td>
<td><%= listing.description %> </td>
<td><%= listing.price %> </td>
<td><%= link_to 'Features', user_listing_features_path(@user,listing) %></td>
<td><%= link_to 'Pictures', user_listing_pictures_path(@user, listing) %></td>
<td><%= link_to 'Edit', user_edit_listing_path(@user, listing) %></td>
<td><%= link_to 'Delete', listing, method: :delete, data: {confirm: 'Are you sure?'} %> </td>
</tr>
<% end %> </tbody>
</table>
<% end %>
</div> </div>

app/views/listings/new.html.erb
<h1>New Listing</h1>
<%= render 'form' %>
<%= link_to 'Back', listings_path %>

app/views/listings/pictures.html.erb
<h1 class="page-heading">All Pictures <small><%= @listing.title %></small> </h1>
<div class="row">
<div class='form-group'>
<div class="col-md-12">
<%=link_to 'New', new_listing_picture_path(@listing), {class: 'btn btn-primary btn-md'}
%>
</div> </div>
<br/>
<div class="row">
<div class="col-md-12">
<% if @pictures.length == 0 %>
<p class="lead">No pictures found </p> <% else %>
<table class="table table-bordered table-striped table-responsive">
<%=link_to 'Gallery', gallery_path(@listing), {class: 'btn btn-primary btn-md'} %> </div>
<thead> <tr>
<td>Title</td> <td></td> </tr>
</thead> <tbody>
<% @pictures.each do |picture| %> <tr>
<td><%= picture.title %> </td>
<td><%= link_to 'Delete', [@listing, picture], method: :delete, data: {confirm: 'Are you sure?'} %> </td>
</tr>
<% end %> </tbody>
</table>
<% end %>
</div>
</div>
<div class="row">
<div class="col-md-12">
<%= link_to 'Back', listings_path %> </div>
</div>

app/views/pictures/details.html.erb
<h1 class='page-heading'>Listing Detail <small><%=@listing.title%></small> </h1>
<div class='row'>
<% picture = @listing.pictures.first %> <% if picture != nil %>
<div class='col-md-8'>
<img class='img-responsive' src='/images/<%=picture.filename%>' alt='picture' />
</div>
<% end %>
<div class='col-md-4'> <h3>Description</h3>
<p><%=@listing.description%></p> <h3>Details</h3>
<ul>
<% @listing.features.each do |feature| %> <li><%= feature.description %></li>
<% end %>
</ul> 
</div>
</div>

app/views/pictures/index.html.erb
<h1 class='page-heading'>All Pictures <small><%=@listing.title%></small> </h1>
<div class="row">
<div class="col-md-12">
<%= link_to 'New',new_listing_picture_path , {class: 'btn btn-primary btn-md'} %> </div>
</div>
<div class="row">
<div class="col-md-12">
<% if @pictures.length == 0 %>
<p class="lead">No pictures found </p> <% else %>
<table class="table table-bordered table-striped table-responsive"> <thead>
<tr> <td>Title</td> <td></td> <td></td> <td></td> </tr>
</thead> <tbody>
<% @pictures.each do |picture| %> <tr>
<td><%= picture.title %> </td>
<td><%= link_to 'Show', listing_picture_path(@listing,picture) %></td>
<td><%= link_to 'Edit', edit_listing_picture_path(@listing,picture) %></td>
<td><%= link_to 'Delete', [@listing,picture], method: :delete, data:{confirm: 'Are you sure'} %></td>
</tr>
<% end %> </tbody>
</table>
<% end %>
</div> </div>

app/views/pictures/show.html.erb
<h1 class='page-heading'>View Picture <small><%=@listing.title %> </small>
</h1>
<p class="lead"><%= @picture.filename %> </p> <div class='row'>
<div class='col-md-4'>
<div class='thumbnail'>
<img src='/images/<%=@picture.filename%>' class='img-responsive' alt='picture'/> <div class='caption'>
<h3><%= @picture.title %></h3> </div>
</div> </div> </div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>